routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/locale/{locale}', 'LanguageController@setLocale')->name('setLocale');

/*
|--------------------------------------------------------------------------
| Folders Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the archive 
|
*/
Route::resource('folder', 'FolderController');
Route::get('folders/trash', 'FolderController@trash')->name('folder.trash');


/*
|--------------------------------------------------------------------------
| Organizations Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the Organization 
|
*/
Route::resource('organization', 'OrganizationController', ['except' => [
     'edit'
]]);
Route::get('organizations/trash', 'OrganizationController@trash')->name('organization.trash');

Route::get('organizations', 'OrganizationController@getAllApi');


/*
|--------------------------------------------------------------------------
| Files Routes (Resource)
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the File 
|
*/
Route::resource('file', 'FileController');

/*
|--------------------------------------------------------------------------
| Media Manager Routes (Resource)
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the File 
|
*/
Route::resource('document', 'DocumentController', ['except' => [
     'edit'
]]);
Route::get('documents/trash', 'DocumentController@trash')->name('document.trash');
Route::get('documents', 'DocumentController@getApi');
Route::post('document/{document}/email', 'DocumentController@email');

/*
|--------------------------------------------------------------------------
| Users Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the User 
|
*/
Route::resource('user', 'UserController', ['only' => [
    'index', 'store','update', 'destroy'
]]);
Route::get('user/profile', 'UserController@profile')->name('user.profile');
Route::get('users/trash', 'UserController@trash')->name('user.trash');

Route::get('user/auth', 'UserController@getAuthUser');
Route::get('users', 'UserController@getAllApi');
Route::get('logout', 'UserController@logout');
Route::get('user/{user}/documents', 'UserController@documents')->name('user.documents');

/*
|--------------------------------------------------------------------------
| Trash Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the User 
|
*/
Route::get('trash/document/{id}/restore', 'TrashController@restoreDocument')->name('document.restore');
Route::get('trash/file/{id}/restore', 'TrashController@restoreFile')->name('file.restore');
Route::get('trash/folder/{id}/restore', 'TrashController@restoreFolder')->name('folder.restore');
Route::get('trash/organization/{id}/restore', 'TrashController@restoreOrganization')->name('organization.restore');
Route::get('trash/user/{id}/restore', 'TrashController@restoreUser')->name('user.restore');

app/Folder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Folder extends Model
{

    use SoftDeletes;   

    protected $dates = ['deleted_at'];

    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'ref', 'desc'
    ];

    /**
     * Eloquent Model Relation
     *
     *@var App\Organization::class
     */
    public function  documents()
    {
        return $this->hasMany('App\Document');
    }

}

app/Http/Controllers/FolderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

use Auth;

use App\Http\Requests\StoreFolderRequest;
use App\Folder;
use App\Organization;
use App\User;

class FolderController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        
        
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trash = false;

        $folders = Folder::all();
        /*foreach ($folders as $key => $value) {
            dd($value->name);
        }*/
        
        return view('folders.index',compact('folders','trash'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function trash()
    {
        $trash = true;

        $folders = Folder::onlyTrashed()->orderBy('deleted_at', 'desc')->get();
        /*foreach ($folders as $key => $value) {
            dd($value->name);
        }*/
        
        return view('folders.index',compact('folders','trash'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Folder $folder)
    {
        $folders = Folder::all();
       return view('folders.create',compact('folder','folders'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreFolderRequest $request)
    {
        $folder = Folder::create($request->all());
        $user = Auth::user();
        Log::info("Folder({$folder->id}): {$folder->name} Craeted by {$user->username}");
        $name = $request->input('name');
        if($request->ajax()){
            return response()->json(['message'=>['title' => __('created').'!', 'desc' => $name.' Created Succesfully'],'folder'=> $folder], 200);
        }else {
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  Folder  $folder
     * @return \Illuminate\Http\Response
     */
    public function show(Folder $folder)
    {
        $trash = false;
        $folders = [];
        $organizations = [];
        $users = User::all();
        $documents = $folder->documents;
        foreach ($documents as $document) {
            $organizations[] = $document->organization;
            $folders[] = $document->folder;
        }
        return view('documents.index', compact('documents','organizations','folders','users','trash'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Folder  $folder
     * @return \Illuminate\Http\Response
     */
    public function edit(Folder $folder)
    {

        $folders = Folder::all();
        return view('folders.create',compact('folder','folders'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Folder $folder)
    {
        $folder->update(['ref' => $folder->ref,'desc'=>$request->desc, 'name' => $request->name]);
        $user = Auth::user();
        Log::info("Folder({$folder->id}): {$folder->name} Updated by {$user->username}");
        return $folder;
     }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( Folder $folder)
    {
        $this->authorize('delete', $folder);

        $name = $folder->name;
        $id = $folder->id;
        /*foreach ($document->files as $file) {//Delete all related Files
            //Keeps  all Files Only Soft Delete 
            if(Storage::disk('s3')->exists($file->slug)) {
                Storage::disk('s3')->delete($file->slug);
            }
            $file->delete();
        }*/
        $folder->documents()->delete();

        if($folder->delete()){
            $user = Auth::user();
            Log::info("Folder({$id}): {$name} Deleted by {$user->username}");
        }

        return response()->json([
            'message'=> $name.' '.__('common.deleted'),
            'title' => __('common.deleted')
            ],200);
    }


    
}

resources/views/folders/_list.blade.php
<div class="panel panel-default card-view">
  <div class="panel-heading">
    <div class="pull-left">
      <h6 class="panel-title txt-dark">{{__('common.folders')}}</h6>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="panel-wrapper collapse in">
    <div class="panel-body">
      <p class="text-muted">{{trans('folder.subtitle')}}</p>
      <div class="table-wrap mt-20">
        <div class="table-responsive">
          <table id="folders" class="table table-hover display mb-30 dataTable no-footer" style="cursor: pointer;" role="grid" aria-describedby="edit_datable_info">
            <thead>
              <tr role="row">
                <th class="sorting_asc" tabindex="0" aria-controls="edit_datable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="{{trans('common.ref')}}: {{trans('common.sort')}}" style="width: 166px;">{{trans('common.ref')}}
                </th>
                <th class="sorting" tabindex="0" aria-controls="edit_datable" rowspan="1" colspan="1" aria-label="{{trans_choice('common.name',1)}}: {{trans('common.sort')}}" style="width: 289px;">{{trans_choice('common.name',1)}}</th>
                <th class="sorting" tabindex="0" aria-controls="edit_datable" rowspan="1" colspan="1" aria-label="{{trans_choice('common.desc',1)}}: {{trans_choice('common.sort',1)}}" style="width: 250px;">{{trans_choice('common.desc',1)}}:
                </th>
              @if($editable)
                <th class="sorting" tabindex="0" aria-controls="datable_1" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending" style="width: 68px;">Action</th>
              @endif
              </tr>
            </thead>
            <tfoot>
              <tr role="row">
                <th class="sorting_asc" tabindex="0" aria-controls="edit_datable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="{{trans('common.ref')}}: {{trans('common.sort')}}" style="width: 166px;">{{trans('common.ref')}}
                </th>
                <th class="sorting" tabindex="0" aria-controls="edit_datable" rowspan="1" colspan="1" aria-label="{{trans_choice('common.name',1)}}: {{trans('common.sort')}}" style="width: 289px;">{{trans_choice('common.name',1)}}</th>
                <th class="sorting" tabindex="0" aria-controls="edit_datable" rowspan="1" colspan="1" aria-label="{{trans_choice('common.desc',1)}}: {{trans_choice('common.sort',1)}}" style="width: 250px;">{{trans_choice('common.desc',1)}}
                </th>
              </tr>   
            </tfoot>
            <tbody>
              @foreach($folders as $key => $folder) 
              <tr role="row" class="odd">
                <td tabindex="1" class="sorting_1">{{$folder->ref}}</td>
                <td tabindex="1">{{$folder->name}}</td>
                <td tabindex="1">{{$folder->desc}}</td>
              @if($editable)
                <td tabindex="1">
                  @if(!$trash)
                    <a href="{{ route('folder.show', ['folder' => $folder->id], false)}}" class="text-inverse pr-5 sa-view" title="view" data-target="tooltip" data-toggle="tooltip" data-original-title="View"   >
                    <i class="zmdi zmdi-eye txt-success"></i>
                    </a>
                    @can('update',$folder)
                      <a href="JavaScript:Void(0)" class="text-inverse pr-10" title="edit" data-id="{{$folder->id}}" data-target="#editModal" data-toggle="modal" data-original-title="Edit" data-ref="{{$folder->ref}}" data-name="{{$folder->name}}" data-desc="{{$folder->desc}}">
                      <i class="zmdi zmdi-edit txt-warning"></i>
                      </a>
                    @endcan

                    @can('delete',$folder)
                      <a href="JavaScript:Void(0)" class="text-inverse sa-delete" title="" data-id="{{$folder->id}}" data-ref="{{$folder->ref}}" data-name="{{$folder->name}}" data-toggle="tooltip" data-original-title="Delete">
                      <i class="zmdi zmdi-delete txt-danger"></i>
                      </a>
                    @endcan
                  @else
                    @can('restore',$folder)
                      <a href="{{ route('folder.restore', ['id' => $folder->id], false)}}"   data-id="{{$folder->id}}" class="text-inverse sa-restore" data-toggle="tooltip"  data-original-title="{{__('common.restore')}}">
                        <i class="zmdi zmdi-undo text-warning zmdi-hc-lg"></i>
                      </a>
                    @endcan
                  @endif
                </td>
              @endif
              </tr>
              @endforeach
            </tbody>
          </table>    
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="editModalLabel">{{__('common.edit')}} {{trans_choice('folder.title',1)}}</h5>
      </div>
      <div class="modal-body">
        {!! Form::open( ['route' => null,'id'=>'editForm','method'=>'patch'])!!}
          <input type="text" name="ref" id="ref" hidden="hidden">
          <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {!!Form::label('name', trans_choice('common.name',1), ['class' => 'control-label mb-10 '])!!}
            {!!Form::text('name',null, ['class'=>'form-control', 'placeholder'=> trans_choice('common.name',1), 'required'=>'required'] )!!}
            {!! $errors->first('name', '<span class ="help-block">:message</span> ') !!}
          </div> 
          <div class="form-group{{ $errors->has('desc') ? ' has-error' : '' }}">
            {!!Form::label('desc', trans_choice('common.desc',1), ['class' => 'control-label mb-10 '])!!}
            {!!Form::textarea('desc',null, ['class'=>'form-control', 'placeholder'=> trans_choice('common.desc',1)] )!!}
            {!! $errors->first('desc', '<span class ="help-block">:message</span> ') !!}
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {!!Form::submit(__('common.save'), ['class'=>'btn btn-primary'])!!}
      </div>
      {!! Form::close()!!}

    </div>
  </div>
</div> 

resources/views/folders/create.blade.php
@extends('layouts.app')

@section('title', trans_choice('folder.title',1))

@section('pageTitle', trans_choice('folder.title',2))

@section('breadcrumb')
  <li><a href="{{route('home')}}">{{trans_choice('navbar.dashboard',1) }}</a></li>
  <li><a href="{{route('folder.index')}}"><span>{{trans_choice('folder.title',2)}}</span></a></li>
  <li class="active"><span>{{__('common.add').' ' .trans_choice('folder.title',1)}}</span></li>
@endsection


@section('content')
  <!-- Row -->
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default card-view ">
        <div class="panel-heading">
          <div class="pull-left">
            <h6 class="panel-title txt-dark">{{__('common.add').' ' .trans_choice('folder.title',1)}}</h6>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="col-sm-12 col-xs-12">
              <div class="form-wrap">
                  {!! Form::open( ['route' => ['folder.store']])!!}
                        {!!Form::token()!!}
                        <div class="form-group{{ $errors->has('ref') ? ' has-error' : '' }}">
                          {!!Form::label('ref', __('common.ref'), ['class' => 'control-label mb-10 '])!!}
                          {!!Form::text('ref',null, ['class'=>'form-control', 'placeholder'=> __('common.ref').' ( 00-01 )', 'required'=>'required'] )!!}
                          {!! $errors->first('ref', '<span class ="help-block">:message</span> ') !!}
                        </div>
                        <div class="form-group{{ $errors->any('name') ? ' has-error' : '' }}">
                          {!!Form::label('name', trans_choice('common.name',1), ['class' => 'control-label mb-10 '])!!}
                          {!!Form::text('name',null, ['class'=>'form-control', 'placeholder'=> trans_choice('common.name',1), 'required'=>'required'] )!!}
                          {!! $errors->first('name', '<span class ="help-block">:message</span> ') !!}
                        </div> 
                        <div class="form-group{{ $errors->any('desc') ? ' has-error' : '' }}">
                          {!!Form::label('desc', trans_choice('common.desc',1), ['class' => 'control-label mb-10 '])!!}
                          {!!Form::textarea('desc',null, ['class'=>'form-control', 'placeholder'=> trans_choice('common.desc',1)] )!!}
                          {!! $errors->first('desc', '<span class ="help-block">:message</span> ') !!}
                        </div>
                        <div class="form-group">
                          {!!Form::submit('Add', ['class'=>'btn btn-info btn-rounded pull-right'])!!}
                        </div> 

                  {!! Form::close()!!}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-8">
      @include('folders._list',['editable'=>true])  
    </div> 
  </div>
  <!-- /Row -->
  
@endsection

@push('scripts')

@endpush

@push('vendorStyles')
    <link href="{{asset('css/datatable.min.css')}}" rel="stylesheet" type="text/css">

    <!--alerts CSS -->
    <link href="{{asset('css/sweetalert.css')}}" rel="stylesheet" type="text/css">
@endpush
@push('scripts')
    <script src="{{asset('js/folder.min.js')}}"></script>

@endpush

resources/views/folders/index.blade.php
@extends('layouts.app')

@section('title', trans_choice('folder.title',1))

@section('pageTitle', trans_choice('folder.title',2))

@section('breadcrumb')
  <li><a href="{{route('home')}}">{{trans_choice('navbar.dashboard',1) }}</a></li>
  <li><a href="{{route('folder.index')}}"><span>{{trans_choice('common.folder',2)}}</span></a></li>
  <li class="active"><span>{{__('common.add').' ' .trans_choice('common.folder',1)}}</span></li>
@endsection


@section('content')
  <!-- Row -->
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default card-view ">
        <div class="panel-heading">
          <div class="pull-left">
            <h6 class="panel-title txt-dark">{{__('common.add').' ' .trans_choice('common.folder',1)}}</h6>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="col-sm-12 col-xs-12">
              <div class="form-wrap">
                  {!! Form::open( ['route' => ['folder.store']])!!}
                        {!!Form::token()!!}
                        <div class="form-group{{ $errors->has('ref') ? ' has-error' : '' }}">
                          {!!Form::label('ref', __('common.ref'), ['class' => 'control-label mb-10 '])!!}
                          {!!Form::text('ref',null, ['class'=>'form-control', 'placeholder'=> __('common.ref').' ( 00-01 )', 'required'=>'required'] )!!}
                          {!! $errors->first('ref', '<span class ="help-block">:message</span> ') !!}
                        </div>
                        <div class="form-group{{ $errors->any('name') ? ' has-error' : '' }}">
                          {!!Form::label('name', trans_choice('common.name',1), ['class' => 'control-label mb-10 '])!!}
                          {!!Form::text('name',null, ['class'=>'form-control', 'placeholder'=> trans_choice('common.name',1), 'required'=>'required'] )!!}
                          {!! $errors->first('name', '<span class ="help-block">:message</span> ') !!}
                        </div> 
                        <div class="form-group{{ $errors->any('desc') ? ' has-error' : '' }}">
                          {!!Form::label('desc', trans_choice('common.desc',1), ['class' => 'control-label mb-10 '])!!}
                          {!!Form::textarea('desc',null, ['class'=>'form-control', 'placeholder'=> trans_choice('common.desc',1)] )!!}
                          {!! $errors->first('desc', '<span class ="help-block">:message</span> ') !!}
                        </div>
                        <div class="form-group">
                          {!!Form::submit('Add', ['class'=>'btn btn-info btn-rounded pull-right'])!!}
                        </div> 

                  {!! Form::close()!!}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-8">
      @include('folders._list',['editable'=>true])  
    </div> 
  </div>
  <!-- /Row -->
  
@endsection

@push('scripts')

@endpush

@push('vendorStyles')
    <link href="{{asset('css/datatable.min.css')}}" rel="stylesheet" type="text/css">

    <!--alerts CSS -->
    <link href="{{asset('css/sweetalert.css')}}" rel="stylesheet" type="text/css">
@endpush
@push('scripts')
    <script src="{{asset('js/folder.min.js')}}"></script>

@endpush