routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/locale/{locale}', 'LanguageController@setLocale')->name('setLocale');

/*
|--------------------------------------------------------------------------
| Folders Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the archive 
|
*/
Route::resource('folder', 'FolderController');
Route::get('folders/trash', 'FolderController@trash')->name('folder.trash');


/*
|--------------------------------------------------------------------------
| Organizations Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the Organization 
|
*/
Route::resource('organization', 'OrganizationController', ['except' => [
     'edit'
]]);
Route::get('organizations/trash', 'OrganizationController@trash')->name('organization.trash');

Route::get('organizations', 'OrganizationController@getAllApi');


/*
|--------------------------------------------------------------------------
| Files Routes (Resource)
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the File 
|
*/
Route::resource('file', 'FileController');

/*
|--------------------------------------------------------------------------
| Media Manager Routes (Resource)
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the File 
|
*/
Route::resource('document', 'DocumentController', ['except' => [
     'edit'
]]);
Route::get('documents/trash', 'DocumentController@trash')->name('document.trash');
Route::get('documents', 'DocumentController@getApi');
Route::post('document/{document}/email', 'DocumentController@email');

/*
|--------------------------------------------------------------------------
| Users Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the User 
|
*/
Route::resource('user', 'UserController', ['only' => [
    'index', 'store','update', 'destroy'
]]);
Route::get('user/profile', 'UserController@profile')->name('user.profile');
Route::get('users/trash', 'UserController@trash')->name('user.trash');

Route::get('user/auth', 'UserController@getAuthUser');
Route::get('users', 'UserController@getAllApi');
Route::get('logout', 'UserController@logout');
Route::get('user/{user}/documents', 'UserController@documents')->name('user.documents');

/*
|--------------------------------------------------------------------------
| Trash Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for the User 
|
*/
Route::get('trash/document/{id}/restore', 'TrashController@restoreDocument')->name('document.restore');
Route::get('trash/file/{id}/restore', 'TrashController@restoreFile')->name('file.restore');
Route::get('trash/folder/{id}/restore', 'TrashController@restoreFolder')->name('folder.restore');
Route::get('trash/organization/{id}/restore', 'TrashController@restoreOrganization')->name('organization.restore');
Route::get('trash/user/{id}/restore', 'TrashController@restoreUser')->name('user.restore');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@yield('title') - {{__('site.longName')}}</title>
    <meta name="description" content="{{config('app.desc')}}" />
    <meta name="keywords" content="belediyesi, lefke belediyesi"/>
    <meta name="author" content="hencework"/>
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
     @stack('vendorStyles')
    <link href="{{asset('vendors/bower_components/jquery-toast-plugin/dist/jquery.toast.min.css')}}" rel="stylesheet" type="text/css">
        
    <!-- Custom CSS -->
    <link href="{{asset('dist/css/style.css')}}" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.8.0/css/flag-icon.css" rel="stylesheet" type="text/css">
    <link href="{{asset('css/custom.css')}}" rel="stylesheet" type="text/css">

    
</head>

<body>
    @include('layouts.header')
    <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">@yield('pageTitle')</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            @yield('breadcrumb')
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->        
            @yield('content')
            @include('layouts.footer')

        </div>
    </div>

resources/views/layouts/footer.blade.php
      <!-- Footer -->

      <footer class="footer container-fluid pl-30 pr-30">
        <div class="row">
          <div class="col-sm-12">
            <p>{{ date('Y')}} &copy; {{config('app.longName')}}. <a href="//www.donpeter.me" target="_blank">Developed By Don Peter Atunalu</a></p>
          </div>
        </div>
      </footer>
      <!-- /Footer -->
    </div>
  </div>
  <!-- /Main Content -->

</div>
<!-- /#wrapper -->
  <!-- JavaScript -->
  
  <!-- jQuery -->
  <script src="{{asset('js/bundle.min.js')}}"></script>

  <script src="{{asset('dist/js/dropdown-bootstrap-extended.js')}}"></script>
  
  <!-- Init JavaScript -->
  <script src="{{asset('dist/js/init.js')}}"></script>
  <!-- Custom Scripts -->
 @stack('scripts')
</body>

</html>

resources/views/layouts/header.blade.php
  <!-- Preloader -->
  <div class="preloader-it">
    <div class="la-anim-1"></div>
  </div>
  <!-- /Preloader -->
    <div class="wrapper theme-4-active pimary-color-red">
    <!-- Top Menu Items -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="mobile-only-brand pull-left">
        <div class="nav-header pull-left">
          <div class="logo-wrap">
            <a href="{{route('home')}}">
              <img class="brand-img" src="{{asset('dist/img/logo.png')}}" alt="brand"/>
              <span class="brand-text">{{__('site.name')}}</span>
            </a>
          </div>
        </div>  
        <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block ml-20 pull-left" href="javascript:void(0);"><i class="zmdi zmdi-menu"></i></a>
      </div>
      <div id="mobile_only_nav" class="mobile-only-nav pull-right">
        <ul class="nav navbar-right top-nav pull-right">
          <li class="dropdown hidden-xs">
            @if (App::isLocale('en'))
                <a data-toggle="dropdown" class="dropdown-toggle menu-item" href="#" aria-expanded="false"><span class="flag-icon flag-icon-gb mr-5"></span>English <span class="caret"></span></a>
              <ul role="menu" class="dropdown-menu">
                  <li>
                    <a href="{{route('setLocale','tr')}}"><span class="flag-icon flag-icon-tr"></span> Türkçe</a>
                  </li>
              </ul>
            @endif
            @if (App::isLocale('tr'))
                <a data-toggle="dropdown" class="dropdown-toggle menu-item" href="#" aria-expanded="false"><span class="flag-icon flag-icon-tr mr-5"></span>Türkçe <span class="caret"></span></a>
                <ul role="menu" class="dropdown-menu">
                  <li>
                   <a href="{{route('setLocale','en')}}"><span class="flag-icon flag-icon-gb"></span> English</a>
                  </li>            
                </ul>
            @endif
              
          </li>
          <li>
            <a href="{{route('user.profile')}}"><i class="zmdi zmdi-account mr-10"></i><span>Profile</span></a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="{{route('logout')}}"><i class="zmdi zmdi-power mr-10"></i><span>{{__('common.logout')}}</span></a>
          </li>
        </ul>
      </div>  
    </nav>
    <!-- /Top Menu Items -->
    @include('layouts.leftmenu')

resources/views/layouts/leftmenu.blade.php
<!-- Left Sidebar Menu -->
<div class="fixed-sidebar-left">
  <ul class="nav navbar-nav side-nav nicescroll-bar">
    <li class="navigation-header">
      <span>Main</span> 
      <i class="zmdi zmdi-more"></i>
    </li>
    <li>
      <a class="{{activePath('/') ? 'active' :''}}" href="/"><div class="pull-left"><i class=" ti-layout-grid2 mr-20"></i><span class="right-nav-text">{{trans_choice('navbar.dashboard',2)}}</span></div><div class="clearfix"></div></a>
    </li>
    <li>
      <a href="javascript:void(0);" class="{{activePath('document') ? 'active' :''}}" data-toggle="collapse" data-target="#nav_document">
        <div class="pull-left">
          <i class=" ti-archive mr-20"></i>
          <span class="right-nav-text">{{__('navbar.documents')}} </span>
        </div>
        <div class="pull-right">
          <i class="zmdi zmdi-caret-down"></i>
        </div>
        <div class="clearfix"></div>
      </a>
      <ul id="nav_document" class="collapse collapse-level-1">
        <li>
          <a href="{{route('document.index')}}" class="{{activePage('document') ? 'active-page' :''}}">
            {{__('navbar.manage').' '.__('navbar.documents') }}
          </a>
        </li>
        <li>
          <a href="{{route('document.create')}}" class="{{activePage('document/create') ? 'active-page' :''}}">
            {{__('common.add').' '.trans_choice('navbar.document', 1) }}
          </a>
        </li>
        <li>
          <a href="{{route('document.trash')}}" class="{{activePage('documents/trash') ? 'active-page' :''}}">
            {{trans_choice('navbar.trash', 1) }}
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0);" class="{{activePath('organization') ? 'active' :''}}" data-toggle="collapse" data-target="#nav_organization"><div class="pull-left"><i class="pe-7s-culture mr-20"></i><span class="right-nav-text">{{__('navbar.organizations')}} </span></div><div class="pull-right"><i class="zmdi zmdi-caret-down"></i></div><div class="clearfix"></div></a>
      <ul id="nav_organization" class="collapse collapse-level-1">
        <li>
          <a href="{{route('organization.index')}}" class="{{activePage('organization') ? 'active-page' :''}}">
            {{__('navbar.manage').' '.__('navbar.organizations') }}
          </a>
        </li>
        <li>
          <a href="{{route('organization.trash')}}" class="{{activePage('organizations/trash') ? 'active-page' :''}}">
            {{__('navbar.trash')}}
          </a>
        </li>
        
      </ul>
      
    </li>
    {{-- <li>
      <a href="javascript:void(0);" data-toggle="collapse" data-target="#app_dr"><div class="pull-left"><i class="pe-7s-photo mr-20"></i><span class="right-nav-text">{{trans_choice('navbar.file',1)}}</span></div><div class="pull-right"><i class="zmdi zmdi-caret-down"></i></div><div class="clearfix"></div></a>
      <ul id="app_dr" class="collapse collapse-level-1">
        <li>
          <a href="{{route('file.index')}}" class="{{activePage('file') ? 'active-page' :''}}">
            {{__('navbar.all').' '.trans_choice('navbar.file', 2) }}
          </a>
        </li>
        <li>
          <a href="{{route('file.create')}}" class="{{activePage('file/create') ? 'active-page' :''}}">
            {{__('navbar.manage').' '.trans_choice('navbar.file', 2) }}

          </a>
        </li>
      </ul>
    </li> --}}
    <li>
      <a class="{{activePath('folder') ? 'active' :''}} " href="javascript:void(0);" data-toggle="collapse" data-target="#nav_folder"><div class="pull-left"><i class="icon-folder-alt mr-20"></i><span class="right-nav-text">{{__('navbar.folders')}} </span></div><div class="pull-right"><i class="zmdi zmdi-caret-down"></i></div><div class="clearfix"></div></a>
      <ul id="nav_folder" class="collapse collapse-level-1">
        <li>
          <a href="{{route('folder.index')}}" class="{{activePage('folder') ? 'active-page' :''}}">
            {{__('navbar.manage').' '.__('navbar.folders') }}
          </a>
        </li>
        <li>
          <a href="{{route('folder.trash')}}" class="{{activePage('folders/trash') ? 'active-page' :''}}">
            {{__('navbar.trash') }}
          </a>
        </li>
        
      </ul>
    </li>
    
    @if(Auth::user()->role === 'admin')
    <li><hr class="light-grey-hr mb-10"/></li>
    <li class="navigation-header">
      <span>{{__('navbar.settings')}}</span> 
      <i class="zmdi zmdi-more"></i>
    </li>
    <li>
      <a href="javascript:void(0);" class="{{activePath('user') ? 'active' :''}}" data-toggle="collapse" data-target="#nav_user"><div class="pull-left"><i class="icon-people mr-20"></i><span class="right-nav-text">{{__('navbar.users')}}</span></div><div class="pull-right"><i class="zmdi zmdi-caret-down"></i></div><div class="clearfix"></div></a>
      <ul id="nav_user" class="collapse collapse-level-1">
        <li>
          <a href="{{route('user.index')}}" class="{{activePage('user') ? 'active-page' :''}}">
            {{__('navbar.manage').' '.__('navbar.users') }}
          </a>
        </li>
        <li>
          <a href="{{route('user.trash')}}" class="{{activePage('users/trash') ? 'active-page' :''}}">
            {{__('navbar.trash') }}
          </a>
        </li>
        
      </ul>
    </li>
   
    <li><hr class="light-grey-hr mb-10"/></li>
    @endif
   
  </ul>
</div>
<!-- /Left Sidebar Menu -->

resources/views/layouts/rightmenu.blade.php
<!-- Right Sidebar Menu -->
<div class="fixed-sidebar-right">
  <ul class="right-sidebar container">
    <a href="javascript:void(0);" class="right-bar-toggle">
        <i class="mdi mdi-close-circle-outline"></i>
    </a>
    <h4 class="">Settings</h4>
    <div class="setting-list nicescroll">
        <div class="row m-t-20">
            <div class="col-xs-8">
                <h5 class="m-0">Notifications</h5>
                <p class="text-muted m-b-0"><small>Do you need them?</small></p>
            </div>
            <div class="col-xs-4 text-right">
                <input type="checkbox" checked data-plugin="switchery" data-color="#7fc1fc" data-size="small"/>
            </div>
        </div>

        <div class="row m-t-20">
            <div class="col-xs-8">
                <h5 class="m-0">Auto Updates</h5>
                <p class="m-b-0 text-muted"><small>Keep up to date</small></p>
            </div>
            <div class="col-xs-4 text-right">
                <input type="checkbox" checked data-plugin="switchery" data-color="#7fc1fc" data-size="small"/>
            </div>
        </div>

        <div class="row m-t-20">
            <div class="col-xs-8">
                <h5 class="m-0">Online Status</h5>
                <p class="m-b-0 text-muted"><small>Show your status to all</small></p>
            </div>
            <div class="col-xs-4 text-right">
                <input type="checkbox" checked data-plugin="switchery" data-color="#7fc1fc" data-size="small"/>
            </div>
        </div>
        <div class="row m-t-20">
            <div class="col-xs-8" data-toggle="collapse" data-target="#app_lang">
                <h5 class="m-0">
                  <a href="javascript:void(0);">Language </a>
                </h5>
                <p class="m-b-0 text-muted" ><small>Choose Language</small></p>
                <ul id="app_lang" class="collapse collapse-level-1">
                  <li>
                    <span class="flag-icon flag-icon-gb mr-10"></span><a href="{{route('setLocale','en')}}">English</a>
                  </li>
                  <li>
                    <span class="flag-icon flag-icon-tr mr-10"></span><a href="{{route('setLocale','tr')}}">Turkish</a>
                  </li>
                </ul>
            </div>
        </div>
    </div>

  </ul>
</div>
</div>
<!-- /Right Sidebar Menu <--> 